### PR TITLE
fix: rework of intl files structure

### LINKED ISSUE #22: intl files structure
Creating this issue to not loose track of https://github.com/ipfs/js.ipfs.io/pull/19#discussion_r199862484

> @PedroMiguelSS upgrade the org of this doc to be separated by sections. Example:

```
{
  nav: {
    // nav stuff
  },
  hero: {
    // hero stuff
  },
  features: {
    list: [
      {
        title: "asjdka",
        description: "asjdka"
      },
      {
        title: "asjdka",
        description: "asjdka"
      },
    ]
  }
  // and so on
}
```

### PR DESCRIPTION
**Pull request by PedroMiguelSS**
This PR updates [`react-intl` files](https://github.com/ipfs/js.ipfs.io/tree/master/intl/messages) structure. Since its structure has changed, the way we use them is slightly different. Thus, this PR updates each file that was accessing these translations keys.

Closes #22

### CODE REVIEW

File: src/shared/components/banner/index.js [hunk 1]
```diff
@@ -16,6 +17,7 @@ class Banner extends Component {
 
   render () {
     const { isOpen } = this.state
+    const { intl: { messages: { banner } } } = this.props
```
Comment (fsdiogo) [inline src/shared/components/banner/index.js]: I think it would be better just to 

```js
const { intl: { messages } } = this.props
```

See my next comment as to why.

File: src/shared/components/banner/index.js [hunk 2]
```diff
@@ -24,8 +26,8 @@ class Banner extends Component {
         </div>
         <div className={ styles.wrapContainer }>
           <div className={ styles.textContainer } >
-            <FormattedMessage tagName="strong" id="bannerHighlightMessage" />
-            <FormattedMessage id="bannerMessage" />
+            <strong>{ banner.highlightMessage }</strong>
```
Comment (fsdiogo) [inline src/shared/components/banner/index.js]: Here you should do:
```js
<strong>{ messages.banner.highlightMessage }</strong>
```

This way is clear that this is a translation, as opposed to the way it is right now. Moreover,  it will be standardised across every component.
