### PR TITLE
Fix/animation performance

### LINKED ISSUE #29: Animation is very CPU hungry
The circling dots animation eats about 200% CPU on my laptop. Makes me close the website right away :(

### PR DESCRIPTION
**Pull request by PedroMiguelSS**
This PR fixes some problems of `hero` section animation such as:
- animated SVGs were being damaged by firefox due to browser optimizations. Somehow, if parts of the image get off the viewport the browser applies an optimization that causes the image to have a "scratchy" look. Thus, when images were animated to cause a spin looking, a user was able to see that images were "scratchy" at some parts. To solve that, images are now set as `background-image` instead of ``. 
- CPU usage was at a considerable percentage. We were trying to solve it by using an approach that automatically disables the animation on low-end devices. However, this task requires both further study and time in order to be correctly implemented. To solve this, we've added a button on `hero` section to allow users to enable/disable animation. To promote a better UX, the state is stored on `local storage`.

This PR closes #29.

### CODE REVIEW

File: src/shared/components/hero-section/helpers/animation-toggle/index.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+  return (
+    <div className={ buttonClasses } onClick={ handleClick }>
+      { title }
+    </div>
+  )
+}
+
+AnimationToggle.propTypes = {
+  className: PropTypes.string,
+  onToggleClick: PropTypes.func,
```
Comment (vasco-santos) [inline src/shared/components/hero-section/helpers/animation-toggle/index.js]: This should be required, and the previous validation will not be needed anymore
